### ISSUE TITLE
Authentication Optimisation

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/Music-Streaming-App#12]
Authentication working in localhost but when it is deployed, it does not work

**Comment by fiskryeziu** [comment]
May I take a closer look at the issue? Could you please provide more specific details? Is the problem related to logging, redirection, or something else within the authentication process?

**Comment by fiskryeziu** [comment]
What service for the backend you using.Where did you deployed, I'm gonna try deploy it myself and see what the problem is.

**Comment by ojasaklechayt** [comment]
> What service for the backend you using.Where did you deployed, I'm gonna try deploy it myself and see what the problem is.

For backend I am using Render and for Frontend I am using Vercel

**Comment by fiskryeziu** [comment]
@ojasaklechayt apperantly the cookies are not being saved on the frontend that's why it's not working. It seems to be a problem with the onrender.com  public suffix domain, you need to have a custom domain to be able to save the cookies on Render services.

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt apperantly the cookies are not being saved on the frontend that's why it's not working. It seems to be a problem with the onrender.com  public suffix domain, you need to have a custom domain to be able to save the cookies on Render services.

I see should I try deploying my backend on some other service ?

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt apperantly the cookies are not being saved on the frontend that's why it's not working. It seems to be a problem with the onrender.com  public suffix domain, you need to have a custom domain to be able to save the cookies on Render services.

I see should I try deploying my backend on some other service ?

**Comment by fiskryeziu** [comment]
Well yes, I'll test it with railway.app .

**Comment by ojasaklechayt** [comment]
> Well yes, I'll test it with railway.app .

Please do have a look

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt I found a workaround since using res.cookie() in deployment, the cookie wasn't getting saved or remove on reload, what I found to make it work it's when we make the request to login, in the backend on userController we respond with
> 
> ```js
>    const token = await generatejwt(user._id);
>    res.status(200).json({ status: 'success', token });
> ```
> 
> and in frontend we get the response and in handle login we destructure and save the token with Cookie.set (js-cookie library)
> 
> ```js
>            const response = await axios.post('backend-url', formData, {
>                 // added axios options enable sending cookies with the request
>                 withCredentials: true,
>                 headers: { 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json' },
>                 credentials: 'include',
>             });
>             console.log('Login successful:', response);
> 
>             const { token } = response.data
>             if (token) {
>                 Cookies.set('token', token, { expires: 2 / 24 })
>             }
> ```
> 
> and also in middleware.js in NextJs root we make the middleware more secure ,we''ll get the jwt from the cookie and verify with jwt.verify() with token_key='secret123', because anyone can go to chrome> application> setCookie manually with name token and get access. Let me know if you wanna proceed.

So, basically instead of setting the cookie in backend, we are sending that token response to the frontend and their in the frontend we are setting the cookie ?

**Comment by fiskryeziu** [comment]
Yes that's how it works

**Comment by ojasaklechayt** [comment]
> Yes that's how it works

If are sending the token to the frontend then will it be secure enough ?

**Comment by fiskryeziu** [comment]
We either way were sending the token, just directly in cookie from server. we're not sending sensitive information only the token and user._id

**Comment by ojasaklechayt** [comment]
> We either way were sending the token, just directly in cookie from server. we're not sending sensitive information only the token and user._id

Hmm yeah makes sense, then We can proceed with the Cookies.set method of authentication. 👍
