### ISSUE TITLE
Update the CONTRIBUTING.md file and write basic contribution instructions

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/Music-Streaming-App#2]
I have created a CONTRIBUTING.md file kindly write the basic instructions for the contributions

**Comment by geekymehta** [comment]
Hi @ojasaklechayt, i have made some changes in CONTRIBUTION.md and also added a CODE_OF_CONDUCT.md file which is referenced in the prior. Please do let me know if there is change that is needed to be made in my PR. [https://github.com/ojasaklechayt/Music-Streaming-App/pull/3]
