### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by Shuhua-L** [ojasaklechayt/Music-Streaming-App#22]
I suggest a few changes to the README file:

- Add a header section with links to the demo, issues, license, and more
- Add a Table of Contents
- Fix the link in the License section to point to the correct file

Here's a [preview](https://github.com/Shuhua-L/Music-Streaming-App/blob/readme/README.md). If you approve, I'd like to create a PR

**Comment by ojasaklechayt** [comment]
I feel you can go for it
