### ISSUE TITLE
Page UI updated

### ISSUE THREAD

**Issue by Ham12-3** [ojasaklechayt/Music-Streaming-App#26]
I updated the page UI by adding blur containers on some sections `and` aligning them in order

**Comment by ojasaklechayt** [comment]
@Ham12-3 Can you please share some screenshots of it ?

**Comment by Ham12-3** [comment]
![grrovewave](https://github.com/ojasaklechayt/Music-Streaming-App/assets/93613316/3e418f33-4997-439f-870a-f3303c2e6884)

**Comment by ojasaklechayt** [comment]
I would like to go with the previous one only. Thanks for the work may be you can try other issues.

**Comment by Ham12-3** [comment]
Ok, that's fine
