### ISSUE TITLE
User Authentication and Session Management using JWT Token

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/Music-Streaming-App#4]
We are creating jwt token at the backend which is getting stored in the cookie. Now there's an error that we are not able to perform authentication, as we are not receiving cookie in the frontend ( nextjs middleware ). Kindly add the Authentication feature in the website.

**Comment by fiskryeziu** [comment]
I'd be happy to take a look at this issue.

**Comment by ojasaklechayt** [comment]
> I'd be happy to take a look at this issue.

@fiskryeziu go for it 🚀🚀

**Comment by ojasaklechayt** [comment]
@fiskryeziu I have created a middleware.js file in the frontend folder. We have one middleware.js at backend also. Kindly both
